# Generated by Django 6.0.3 on 2026-03-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
