# Generated by Django 6.0.3 on 2026-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictrack_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
    ]
